class Game{
    constructor(){
        this.finshingPoint=createSprite(930,430);
        this.finshingPoint.visible=false;

        this.coins=0;
        this.lives=0;
        this.player=createSprite(80,10);
        this.player.addAnimation("walk",playerAnimation);
        this.player.debug=false;
        this.player.setCollider("rectangle",-20,20,this.player.witdh-50,this.player.height-70);
        this.block1=createSprite(600,10,1000,20);
        this.block1.shapeColor="#5C33F6";
        this.block2=createSprite(990,250,20,500);
        this.block2.shapeColor="#5C33F6";
        this.block3=createSprite(400,490,1000,20);
        this.block3.shapeColor="#5C33F6";
        this.block4=createSprite(10,250,20,500);
        this.block4.shapeColor="#5C33F6";
        this.block5=createSprite(350,100,20,200);
        this.block5.shapeColor="#5C33F6";
        this.block6=createSprite(700,50,20,100);
        this.block6.shapeColor="#5C33F6";
        this.block7=createSprite(70,350,100,20);
        this.block7.shapeColor="#5C33F6";
        this.block8=createSprite(300,200,300,20);
        this.block8.shapeColor="#5C33F6";
        this.block9=createSprite(210,250,20,100);
        this.block9.shapeColor="#5C33F6";
        this.block10=createSprite(140,160,20,100);
        this.block10.shapeColor="#5C33F6";
        this.block11=createSprite(180,120,100,20);
        this.block11.shapeColor="#5C33F6";
        this.block12=createSprite(440,260,20,100);
        this.block12.shapeColor="#5C33F6";
        //this.block13=createSprite(410,300,50,20);
        //this.block13.shapeColor="#5C33F6";
        //this.block14=createSprite(380,315,20,50);
        //this.block14.shapeColor="#5C33F6";
       this.block15=createSprite(320,430,20,100);
        this.block15.shapeColor="#5C33F6";
        this.block16=createSprite(610,430,20,100);
        this.block16.shapeColor="#5C33F6";
        this.block17=createSprite(610,390,200,20);
        this.block17.shapeColor="#5C33F6";
        this.block18=createSprite(710,350,20,100);
        this.block18.shapeColor="#5C33F6";
        this.block19=createSprite(730,300,200,20);
        this.block19.shapeColor="#5C33F6";
        this.block20=createSprite(820,240,20,100);
        this.block20.shapeColor="#5C33F6";
        this.block21=createSprite(930,390,100,20);
        this.block21.shapeColor="#5C33F6";

        this.coin1=createSprite(80,420,10,10);
        this.coin1.addImage(coinImage);
        this.coin1.scale=0.07;
        this.coin2=createSprite(500,110,10,10);
        this.coin2.addImage(coinImage);
        this.coin2.scale=0.07;
        this.coin3=createSprite(630,360,10,10);
        this.coin3.addImage(coinImage);
        this.coin3.scale=0.07;
        this.coin4=createSprite(660,450,10,10);
        this.coin4.addImage(coinImage);
        this.coin4.scale=0.07;
        this.coin5=createSprite(820,60,10,10);
        this.coin5.addImage(coinImage);
        this.coin5.scale=0.07;
        this.coin6=createSprite(270,118,10,10);
        this.coin6.addImage(coinImage);
        this.coin6.scale=0.07;
    }
    controls(){
        if(keyIsDown(UP_ARROW)){
            this.player.y=this.player.y-5;
        }
        if(keyIsDown(DOWN_ARROW)){
            this.player.y=this.player.y+5;
        }
        if(keyIsDown(LEFT_ARROW)){
            this.player.x=this.player.x-5;
        }
        if(keyIsDown(RIGHT_ARROW)){
            this.player.x=this.player.x+5;
        }
    }
    hide(){
        this.block1.visible=false;
        this.block2.visible=false;
        this.block3.visible=false;
        this.block4.visible=false;
        this.block5.visible=false;
        this.block6.visible=false;
        this.block7.visible=false;
        this.block8.visible=false;
        this.block9.visible=false;
        this.block10.visible=false;
        this.block11.visible=false;
        this.block12.visible=false;
        this.block15.visible=false;
        this.block16.visible=false;
        this.block17.visible=false;
        this.block18.visible=false;
        this.block19.visible=false;
        this.block20.visible=false;
        this.block21.visible=false;
        this.player.visible=false;
        this.coin1.visible=false;
        this.coin2.visible=false;
        this.coin3.visible=false;
        this.coin4.visible=false;
        this.coin5.visible=false;
        this.coin6.visible=false;
    }
    visible(){
        this.block1.visible=true;
        this.block2.visible=true;
        this.block3.visible=true;
        this.block4.visible=true;
        this.block5.visible=true;
        this.block6.visible=true;
        this.block7.visible=true;
        this.block8.visible=true;
        this.block9.visible=true;
        this.block10.visible=true;
        this.block11.visible=true;
        this.block12.visible=true;
        this.block15.visible=true;
        this.block16.visible=true;
        this.block17.visible=true;
        this.block18.visible=true;
        this.block19.visible=true;
        this.block20.visible=true;
        this.block21.visible=true;
        this.player.visible=true; 
        this.coin1.visible=true;  
        this.coin2.visible=true;
        this.coin3.visible=true;
        this.coin4.visible=true;
        this.coin5.visible=true;
        this.coin6.visible=true;
    }
    start(){
        this.hide();
        textSize(50);
        fill("black");
        text("ROUGE RUNNER",width/2-200,height/2);
        textSize(30);
        text("Press the longest button ",width/2-150,height/2+50);
        if(keyIsDown(32)){
            gameState="play";
        }
    }
    play(){
        this.controls();
        this.visible();
        if(this.player.isTouching(this.block1)||
         this.player.isTouching(this.block2)||
         this.player.isTouching(this.block3)||
         this.player.isTouching(this.block4)||
         this.player.isTouching(this.block5)||
         this.player.isTouching(this.block6)||
         this.player.isTouching(this.block7)||
         this.player.isTouching(this.block8)||
         this.player.isTouching(this.block9)||
         this.player.isTouching(this.block10)||
         this.player.isTouching(this.block11)||
         this.player.isTouching(this.block12)||
         this.player.isTouching(this.block15)||
         this.player.isTouching(this.block16)||
         this.player.isTouching(this.block17)||
         this.player.isTouching(this.block18)||
         this.player.isTouching(this.block19)||
         this.player.isTouching(this.block20)||
         this.player.isTouching(this.block21)){
             this.player.x=80;
             this.player.y=10;
             this.lives++;
             hitSound.play();
         }
         if(this.player.isTouching(this.coin1)){
             this.coin1.destroy();
             this.coins++;
             goldieSound.play();
         }
         if(this.player.isTouching(this.coin2)){
            this.coin2.destroy();
            this.coins++;
            goldieSound.play();
        }
        if(this.player.isTouching(this.coin4)){
            this.coin4.destroy();
            this.coins++;
            goldieSound.play();
        }
        if(this.player.isTouching(this.coin3)){
            this.coin3.destroy();
            this.coins++;
            goldieSound.play();
        }
        if(this.player.isTouching(this.coin5)){
            this.coin5.destroy();
            this.coins++;
            goldieSound.play();
        }
        if(this.player.isTouching(this.coin6)){
            this.coin6.destroy();
            this.coins++;
            goldieSound.play();
        }
        if(this.lives===3){
            gameState="end";   
        }
        if(this.coins===6&&this.player.isTouching(this.finshingPoint)){
            gameState="win";
        }
    }
    end(){
        fill("green");
        textSize(30);
        text("LEAVE NOW",width/2,height/2);
        this.hide();
    }
    win(){
        fill("green");
        textSize(30);
        text("LEAVE NOW",width/2,height/2);
        this.hide();
    }
}